### ISSUE TITLE
 Cornerstone problems

### ISSUE THREAD

**Issue by robk123** [yasglobal/custom-permalinks#10]
I wasn't sure what the best place to report a bug would be so i reposted the bug here as well.

As stated in this topic: https://wordpress.org/support/topic/conflict-with-cornerstone/.

The problem is still here.

When using your plugin I cannot edit my page inside cornerstone.

See this image for the error: https://ibb.co/mUrRQ7

The moment I disable your plugin it works fine.

Can you please tell me if this issue will be resolved any time soon?

Thank you.

**Comment by samiahmedsiddiqui** [comment]
Hi @robk123 

Thanks for reporting this issue and sorry about the delay in my response.

Can you tell me which theme you are using? As i can't see this issue on storefront or twenty seventeen.  I am using Free Version of the Cornerstone plugin.

Could you guide me how to reach to this content layout if it part of the cornerstone?

Thanks,
Sami
