### ISSUE TITLE
Line 105 Breaking Change

### ISSUE THREAD

**Issue by skowronek** [yasglobal/custom-permalinks#11]
For the following url:

www.domain.com/contact-us/feedback (etc.)

This code is a breaking change. Needs to look only at the END of the path, not the entire path.

Many ways to accomplish. If we get a chance to submit pull request we will.

```
    $post_feed = 0;
    **if ( false !== strpos( $request_noslash, '/feed' ) ) {**
      $request_noslash = str_replace( '/feed', '', $request_noslash );
      $post_feed = 1;
    }
```

**Comment by samiahmedsiddiqui** [comment]
@skowronek Thanks for pointing this out.

Plugin doesn't need these lines anymore. I have removed these lines and hopefully that resolves the issue.

Thanks,
Sami

**Comment by samiahmedsiddiqui** [comment]
@skowronek Please check the latest version and provide your feedback to me.

Thanks,
Sami

**Comment by skowronek** [comment]
Thanks @samiahmedsiddiqui .
