### ISSUE TITLE
Capability not recognized

### ISSUE THREAD

**Issue by 5A5K1A** [yasglobal/custom-permalinks#12]
Since the capabilities of the admin pages are set to `administrator` we encountered a problem with the "super administrator" role we created ourselves.
I therefor vote for replacing `administrator` with one of the capabilities found on [Roles & Capabilities](https://codex.wordpress.org/Roles_and_Capabilities#Capability_vs._Role_Table) in the WordPress Codex.

* `administrator` can be found in custom-permalinks/admin/class-custom-permalinks-about.php r.26, r.31, r.35 & r.39

**Comment by samiahmedsiddiqui** [comment]
@5A5K1A Capabilities added. There are 2 different Capabilities. One to view the PostTypes Permalinks and another is to view the Category Permalinks. 

You can specify the Capabilities according to your requirement. In default these capabilities are defined for the administrator.
