### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by RaymondAngana** [yasglobal/custom-permalinks#13]
Hi,

Good day!

Custom-permalinks work great but I'm having real trouble with Windows Server with URL Rewrite 2.1 installed.

WP's custom permalink works just fine. I'm getting URL like `/highlight-1234` but not `/highlight/1234`.

Can you please let me know if there's anything else needed apart from IIS' url-rewrite?

Hoping to hear from you.

**Comment by samiahmedsiddiqui** [comment]
HI @RaymondAngana 

What's the issue you are facing on with Windows Server?

I have tested the plugin on installing the WordPress in the local machine on Windows 10 and everything looks fine to me.

Let me know, what issues you are facing on.

Thanks,
Sami
