### ISSUE TITLE
Home Page is redirecting to a product page

### ISSUE THREAD

**Issue by animatrio** [yasglobal/custom-permalinks#20]
Home Page (main site URL) is redirecting to a particular product page after update. 
Both customers and admin are unable to access/see Home Page on front end. 

Check the website - 
HOME (redirects to a product)- https://www.grootgadgets.com/
Temporary HOME (till issue resolves) - https://www.grootgadgets.com/shop/

Issue goes away after only after deactivating the plugin. Please fix this asap. thanks

**Comment by samiahmedsiddiqui** [comment]
@animatrio Please download this file replace it with the current file.
[class-custom-permalinks-frontend.php](https://github.com/yasglobal/custom-permalinks/blob/develop/frontend/class-custom-permalinks-frontend.php)

This is the only change i know which may effect the Permalinks from the previous version.

Let me know the results.

Thanks,
Sami

**Comment by animatrio** [comment]
I will do it in a few hours. Thanks.

**Comment by animatrio** [comment]
Hi, I opened this link and there is no option to download the file.
Also please tell me where do I need to replace this file exactly?

**Comment by animatrio** [comment]
I replaced the file, but there is no change. Its acting the same way

**Comment by samiahmedsiddiqui** [comment]
@animatrio Have you changed settings of the HomePage from the WP Settings or it is same? Can you provide the WordPress HomePage Settings screenshot?

**Comment by animatrio** [comment]
No change made in home page settings.

**Comment by samiahmedsiddiqui** [comment]
@animatrio I mean have you changed the selection from this page:
![image](https://user-images.githubusercontent.com/16156106/48994740-a743d980-f166-11e8-878c-38e728e4f122.png)

This is the page from where you can select which page to show as your homepage. Please check that.

Regards,
Sami

**Comment by animatrio** [comment]
Yes, on this page base url is selected as it should be.

**Comment by animatrio** [comment]
By any chance this plugin can create a 301 Redirect by mistake? 
If yes, then how can i delete it?

**Comment by samiahmedsiddiqui** [comment]
@animatrio What's your "Groot Gadget" URL which is selected as Homepage? One more suggestion, Create a test page and change your homepage to point to the test page and then resave your settings by changing it to your proper Homepage. It may takes one minute to test either it works or not.

> By any chance this plugin can create a 301 Redirect by mistake?
> If yes, then how can i delete it?
This plugin doesn't create any redirect by itself or anyhow.

**Comment by animatrio** [comment]
Groot Gadgets URL = https://www.grootgadgets.com/ = Home URL

And the latest suggestion did not work. Infact when I changed the home page to point to test page, it failed to load anything showing some error.

**Comment by animatrio** [comment]
I deleted and replaced the Custom Permalinks plugin. Thanks for your time
but my patience has run out. Site is working fine after deleting it.

**Comment by samiahmedsiddiqui** [comment]
@animatrio OK.
