### ISSUE TITLE
Plugin Allows for Extraneous Information in URL

### ISSUE THREAD

**Issue by kikoking1** [yasglobal/custom-permalinks#3]
Consider the following url:
`http://mysite.ca/running-child.http://www`

Let's say that page above has a parent page of Running - `http://mysite.ca/running`, which would normally make it `http://dig.mediabot.ca/running/running-child` 
But with the Custom Permalink plugin, I have removed the first part of the url to make it simply `/running-child` instead of `/running/running-child`
With the shorter url now comes the vulnerability. The url /running-child will now load it's normal desired page, but if I put something like `/running-childICanPutAnythingIwantRightHere` that will also load a page as well.

It seems that the Custom Permalinks plugin messes up some of the security of the url so that it doesn't throw 404 properly if the url doesn't match exactly the desired page slug. So pretty much, if the url starts with the correct slug, it will load a page even if there is a bunch of other crap info after that in the url.

The Issue:
My client's site has had someone take advantage of this, and has somehow caused a page to be indexed in the Google serps that doesn't technically exist for their site, but was still indexed by Google because it didn't throw a 404, and still loaded a page. The url looked something like this - `/page-name-here.EXTRANEOUS+INFO+RIGHT+HEREhttp:/www.weirddomain.my`

This is bad because now there are two pages indexed by google with the similar content, when there shouldn't be. Not only that but that could be indexed an infinite amount of times, putting much more than 2 pages indexed, with possibly provocative and unsightly info in the url's in the serps.

**This is a huge vulnerability for anyone using this plugin.**

**Comment by samiahmedsiddiqui** [comment]
@kikoking1 Thanks for reporting the issue.

I have created 2 pages. Parent Page is "/running" and the child page is "/running-child". When i add any string in the URL it gives the 404 to me.

Like: 

1. http://example.com/running-child.http
2. http://example.com/running-child-sami
3. http://example.com/aa/running-child

Please help me to generate this issue so, i can fix this out.

Regards,
Sami

**Comment by kikoking1** [comment]
Thank you for your reply! I am very grateful for your help with this.

Can you try this
http://example.com/running-child.http://www.

**Comment by samiahmedsiddiqui** [comment]
@kikoking1 Checked. But still don't get any issue.
Original URL: http://example.com/running-child (Returns status 200)
Checked URL: http://example.com/running-child.http:/www (Returns status 404)

**Comment by samiahmedsiddiqui** [comment]
@kikoking1 Suggest you to install Fresh WordPress on your local server and install the Custom Permalinks Plugin and try to generate the issue there. 

If you doesn't found the issue then there is some conflict with your theme or some other plugin. If you successfully generated the issue so, kindly provide the steps to produce the issue.

Regards,
Sami

**Comment by samiahmedsiddiqui** [comment]
@k1sul1 Are you also getting some sort of issue?

**Comment by kikoking1** [comment]
@samiahmedsiddiqui thank you so much for working on this issue. I thought I had it nailed down to this plugin, but it may seem that this might not be the case. I'll dig a little more and try to figure out what is causing this issue on our site, it may be a combination of things. Forgive me for not putting a lot of immediate time into this as I am pretty insanely busy right now. I will try to reproduce the issue on a fresh install etc and get back here as soon as possible.

**Comment by samiahmedsiddiqui** [comment]
@kikoking1 I have released the new version and one of the user is confirmed that this duplication content issue has been resolved.

So, whenever you get time, give it a try of the latest version which is v1.2.10 now and provide your feedback accordingly.

Thanks,
Sami
