### ISSUE TITLE
'View" button for previewing custom post types should use 'view_item' label defined when custom post type is registered

### ISSUE THREAD

**Issue by spinfly** [yasglobal/custom-permalinks#31]
Currently, the "View ..." button on admin pages uses ucfirst( $post->post_type ). This looks clunky when usings a custom post type like 'press_releases'. See attached screenshot.

My recommendation is to use the 'view_item' label that is defined when a post type is registered for this button.

The code to be modified is here:

custom-permalinks/frontend/class-custom-permalinks-form.php
Lines 180 and 238

**Comment by samiahmedsiddiqui** [comment]
@spinfly Done, sorry I didn't review this issue before, just fixed and will available in the upcoming in the next few days.
