### ISSUE TITLE
PHP 7.4 - replace {} with [] on 499 and 500

### ISSUE THREAD

**Issue by julian-sloman-ffatg** [yasglobal/custom-permalinks#32]
Hi Sami,

As per [WP Support topic](https://wordpress.org/support/topic/php-7-4-support-4/) there's still some PHP 7.4 compatibility issues that need to be sorted out. This one is easy:

`/wp-content/plugins/custom-permalinks/frontend/class-custom-permalinks-frontend.php` on lines 499 and 500 uses `{` curly brackets `}` instead of `[` square ones `]` which makes PHP 7.4 upset, since it's depreciated.

$string **{** 0 **}**

```
if ( trim( $_CPRegisteredURL, '/' ) == trim( $request, '/' ) ) {
      if ( isset( $url['path'] ) ) {
        return ( $string{0} == '/' ? '/' : '' ) . trailingslashit( $url['path'] ) . $_CPRegisteredURL;
      } else {
        return ( $string{0} == '/' ? '/' : '' ) . $_CPRegisteredURL;
      }
    }
    return $string;
```

**Comment by samiahmedsiddiqui** [comment]
@julian-sloman-ffatg Thank you for reporting this issue and sorry about my late response. I have fixed this issue and the fix will be released soon with a bunch of other things.
