### ISSUE TITLE
Deprecated: category_link

### ISSUE THREAD

**Issue by MasterNS** [yasglobal/custom-permalinks#34]
After upgrade to WP 5.4 following error is generated across site (both dashboard and frontend): **Deprecated: category_link is deprecated since version 2.5.0! Use term_link instead**
please update/replace deprecated functions

**Comment by samiahmedsiddiqui** [comment]
@MasterNS Thank you for reporting this issue and sorry about my late response. I have fixed this issue and the fix will be released soon with a bunch of other things.

**Comment by AndyS7A** [comment]
When is the release that includes this fix?

**Comment by samiahmedsiddiqui** [comment]
@MasterNS It is going to be released tonight or tomorrow.
