### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by codyjoliphant** [yasglobal/custom-permalinks#5]
It appears that Pagination on Child Pages is broken. For example, if I have a child page with the custom permalink **example.com/custom/**, the link **example.com/custom/page/2/** will not work.

This is not an issue in version 1.2.8, fyi.

**Comment by samiahmedsiddiqui** [comment]
@codyjoliphant Issue is fixed in the v1.2.11. Please verify the issue at your end.

Thanks

**Comment by codyjoliphant** [comment]
@samiahmedsiddiqui The issue seems to be resolved in v1.2.11. Thanks!

**Comment by samiahmedsiddiqui** [comment]
@codyjoliphant Thanks for you confirmation. Have a good day..!

**Comment by samiahmedsiddiqui** [comment]
@codyjoliphant Kindly Check the v1.2.12. I have just released the version and one of the customer confirmed that the issue is fixed for him.

You can check at your end.

**Comment by codyjoliphant** [comment]
@samiahmedsiddiqui Looks like it's all good now. Thanks again.

**Comment by samiahmedsiddiqui** [comment]
@codyjoliphant Thanks for the quick response and providing your feedback. 💯 

Have a good day 😄

**Comment by sdwkn** [comment]
It's still broken.

**Comment by samiahmedsiddiqui** [comment]
@sdwkn What's the issue you are facing? Can you please define?

Also, please mention the version of your WordPress and the plugin.
