### ISSUE TITLE
post or product category permalink settings not working after last update

### ISSUE THREAD

**Issue by palesz107** [yasglobal/custom-permalinks#7]
Hi :) 

I want to modify my post category peramlink.
I changed the default permalink to my custom text.  But after when i click the saves don't changed the url! 

Did you found this bug before?

**Comment by samiahmedsiddiqui** [comment]
Hi @palesz107 

Are you working on default category or custom category? If you are working on the default category then it works fine. But, if you are using Custom Category or Product category so, the plugin doesn't works on that.

Custom Category and Product Category would be supported in the future releases.

Let me know your feedback on it.

Thanks,
Sami

**Comment by palesz107** [comment]
Hi @samiahmedsiddiqui  :) 
ohh yes, I tried in costom and product Category.  Sorry i don't know that . Thank you :)

**Comment by palesz107** [comment]
I using  long tim ago. Currently we rebulid our webpage. 
I have 49 PostTypes Permalinks.

**Comment by samiahmedsiddiqui** [comment]
@palesz107 Not sure how important the category/product permalink is for you.

But, if it is much important so, i recommend you to try the Permalinks Customizer Plugin. Make sure to deactivate the Custom Permalinks Plugin and then activate Permalinks Customizer (If you like to use).

For the current custom permalinks, you can migrate them to Permalinks Customizer using batch script option under Permalinks Customizer plugin.
