### ISSUE TITLE
Custom permalinks breaks Woocommerce Review pagination

### ISSUE THREAD

**Issue by jhartsoch** [yasglobal/custom-permalinks#9]
Custom permalinks breaks Woocommerce Review pagination

1) Go here and select reviews tab
https://www.fairhavendev.com/3pregtesstri  (this product uses a custom permalink)

2) Select page 3 of reviews at bottom
https://www.fairhavendev.com/3pregtesstri/comment-page-3#tab-reviews

3) Note that the /comment-page-3/ part of the slug gets stripped off by Custom Permalinks and effectively breaks pagination

repros on a clean current install with default storefront theme as well.  If custom permalinks is disabled, or the particular product/post DOES NOT utilize a custom permalink, it works fine.  Have not tested with standard wordpress comments but they may also have an issue.

Thanks!

**Comment by samiahmedsiddiqui** [comment]
@jhartsoch Thank you for pointing this out.

I have fixed the issue and release the version 1.2.17. Please take a look of the latest version and provide your valuable feedback.

Thanks
